// ──────────────────────────────────────────────────────────────────────────
// Client-side demo engine — a faithful JS port of backend/app/services/demo_engine.py.
// This is what makes CloudPilot "just work" on Cloudflare Pages with no backend:
// the entire placeholder experience runs in the browser, derived from the actual
// graph the user drew. Real mode (BYOK / operator) routes to the Pages Function;
// everything here is the zero-credential fallback.
// ──────────────────────────────────────────────────────────────────────────
import { FALLBACK_CATALOG } from "../data/fallbackCatalog.js";

export const CATALOG = FALLBACK_CATALOG;

const PRICE = {
  cloud_run: 86.4, gke: 292.0, cloud_functions: 12.8, compute_engine: 168.7, cloud_sql: 246.3,
  bigquery: 121.9, firestore: 33.2, gcs: 18.6, memorystore: 97.1, vertex_ai: 204.5,
  gemini: 158.2, discovery_engine: 88.0, load_balancer: 36.5, vpc: 0.0, cloud_armor: 64.0,
  api_gateway: 22.4, pubsub: 41.7, cloud_tasks: 9.3, secret_manager: 3.1, kms: 6.0,
};

const TF = {
  cloud_run: (n) => `resource "google_cloud_run_v2_service" "${n}" {
  name     = "${n}"
  location = var.region
  template {
    containers {
      image = "gcr.io/\${var.project_id}/${n}:latest"
      resources { limits = { cpu = "2", memory = "1Gi" } }
    }
    scaling { min_instance_count = 1, max_instance_count = 20 }
  }
  ingress = "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
}`,
  cloud_sql: (n) => `resource "google_sql_database_instance" "${n}" {
  name             = "${n}"
  database_version = "POSTGRES_16"
  region           = var.region
  settings {
    tier = "db-custom-2-8192"
    ip_configuration {
      ipv4_enabled    = false
      private_network = google_compute_network.vpc.id
    }
    backup_configuration { enabled = true, point_in_time_recovery_enabled = true }
  }
}`,
  load_balancer: (n) => `resource "google_compute_global_forwarding_rule" "${n}" {
  name       = "${n}"
  target     = google_compute_target_https_proxy.${n}_proxy.id
  port_range = "443"
}`,
  pubsub: (n) => `resource "google_pubsub_topic" "${n}" {
  name = "${n}"
  message_retention_duration = "86600s"
}`,
  gcs: (n) => `resource "google_storage_bucket" "${n}" {
  name                        = "\${var.project_id}-${n}"
  location                    = "US"
  uniform_bucket_level_access = true
  versioning { enabled = true }
}`,
  bigquery: (n) => `resource "google_bigquery_dataset" "${n}" {
  dataset_id    = "${n.replace(/-/g, "_")}"
  location      = "US"
}`,
  vpc: () => `resource "google_compute_network" "vpc" {
  name                    = "vpc"
  auto_create_subnetworks = false
}`,
  gemini: (n) => `# Gemini is consumed via Vertex AI — grant the runtime SA access
resource "google_project_iam_member" "${n}_user" {
  project = var.project_id
  role    = "roles/aiplatform.user"
  member  = "serviceAccount:\${google_service_account.runtime.email}"
}`,
};
const tfGeneric = (n, t) => `resource "google_${t}" "${n}" {
  # Generated by CloudPilot · Gemini architect
  name    = "${n}"
  project = var.project_id
}`;

const slug = (label) => label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

function seedOf(graph) {
  const payload = graph.nodes.map((n) => n.id).sort().join(",");
  let h = 0;
  for (let i = 0; i < payload.length; i++) h = (h * 31 + payload.charCodeAt(i)) >>> 0;
  return h;
}

const MAX_TOKENS = 2_097_152;

export function generate(graph, project = {}, model = "gemini-2.5-pro") {
  const nodes = graph.nodes || [];
  const edges = graph.edges || [];
  const seed = seedOf(graph);
  const n = Math.max(nodes.length, 1);
  const types = new Set(nodes.map((x) => x.type));

  const sources = [
    { name: "Enterprise Standards Corpus (Discovery Engine)", tokens: 412019 },
    { name: "Org Policy & IAM Snapshot", tokens: 188404 },
    { name: "Live Terraform State (entire estate)", tokens: 521337 + (seed % 9000) },
    { name: "Historical Incident Postmortems", tokens: 96812 },
    { name: "Architecture Graph + Canvas Intent", tokens: 1900 * n },
  ];
  const used = sources.reduce((a, s) => a + s.tokens, 0);

  const reasoning = [
    { phase: "INGEST", text: `Ingested ${used.toLocaleString()} tokens in a single pass — full standards corpus, org policy snapshot and live Terraform state. No RAG chunking required at this scale.` },
    { phase: "PARSE", text: `Parsed canvas graph: ${nodes.length} services, ${edges.length} connections. Topology classified as ${types.has("pubsub") ? "event-driven microservice mesh." : "tiered web service."}` },
    { phase: "GROUND", text: "Cross-referenced design against 147 enterprise standards via Discovery Engine grounding. 3 standards directly constrain this topology." },
  ];
  if (types.has("cloud_sql")) reasoning.push({ phase: "GROUND", text: "Standard SEC-004 mandates private-IP-only databases — enforcing ipv4_enabled = false and VPC peering on Cloud SQL." });
  if (types.has("cloud_run")) reasoning.push({ phase: "DESIGN", text: "Cloud Run ingress restricted to the internal load balancer; min instances pinned to 1 to meet RES-011 cold-start SLO." });
  reasoning.push(
    { phase: "DESIGN", text: "Synthesized least-privilege IAM: one runtime service account per workload, no primitive roles (IAM-002)." },
    { phase: "VERIFY", text: "Replayed 12 historical incident postmortems against the proposed design — no recurrence vectors detected." },
    { phase: "EMIT", text: `Emitting ${n + 2} Terraform resources with cost annotations and a Cloud Build deployment pipeline.` }
  );

  const blocks = [
    `terraform {
  required_providers {
    google = { source = "hashicorp/google", version = "~> 6.0" }
  }
}

variable "project_id" { type = string }
variable "region"     { type = string, default = "${project.region || "us-central1"}" }

resource "google_service_account" "runtime" {
  account_id   = "cloudpilot-runtime"
  display_name = "CloudPilot runtime (least privilege)"
}`,
  ];
  for (const nd of nodes) {
    const name = slug(nd.label);
    const make = TF[nd.type];
    blocks.push(make ? make(name) : tfGeneric(name, nd.type));
  }
  const mainTf = blocks.join("\n\n") + "\n";

  const findings = [
    { id: "f-iam", severity: "PASS", standard: "IAM-002", title: "Least-privilege service accounts", detail: "Dedicated runtime SA generated; zero primitive roles in plan.", autofix: false },
    { id: "f-enc", severity: "PASS", standard: "SEC-001", title: "Encryption at rest", detail: "All stateful services use Google-managed CMEK-ready encryption.", autofix: false },
  ];
  if (types.has("cloud_sql")) findings.push({ id: "f-sql", severity: "PASS", standard: "SEC-004", title: "Database network isolation", detail: "Cloud SQL pinned to private IP with VPC peering — public path removed by Gemini during synthesis.", autofix: false });
  if (types.has("load_balancer") && !types.has("cloud_armor")) findings.push({ id: "f-waf", severity: "WARN", standard: "SEC-009", title: "Edge missing WAF", detail: "Global LB has no Cloud Armor policy attached. Gemini can inject a baseline OWASP rule set.", autofix: true });
  if (types.has("compute_engine")) findings.push({ id: "f-vm", severity: "WARN", standard: "COST-003", title: "Unattended VM rightsizing", detail: "Compute Engine without an autoscaler violates cost guardrail COST-003.", autofix: true });
  if (!types.has("vpc") && (types.has("cloud_sql") || types.has("memorystore"))) findings.push({ id: "f-vpc", severity: "BLOCK", standard: "NET-001", title: "Private services require a VPC", detail: "Stateful private services present but no VPC on canvas. Drag a VPC node or accept Gemini's autofix.", autofix: true });
  const score = Math.max(40, 100 - findings.reduce((a, f) => a + (f.severity === "WARN" ? 6 : f.severity === "BLOCK" ? 25 : 0), 0));

  const breakdown = nodes.map((nd) => ({ service: nd.label, usd: PRICE[nd.type] ?? 25.0 }));
  const monthly = Math.round(breakdown.reduce((a, b) => a + b.usd, 0) * 100) / 100;

  return {
    run_id: `run-${Math.random().toString(36).slice(2, 12)}`,
    model,
    context_window: { used, max: MAX_TOKENS, sources },
    reasoning,
    iac: { language: "terraform", files: [{ path: "main.tf", content: mainTf }] },
    compliance: { score, findings },
    cost_estimate: { monthly_usd: monthly, breakdown },
    summary: `Designed a ${nodes.length}-service architecture grounded in 147 enterprise standards, emitted ${n + 2} Terraform resources, projected $${monthly.toLocaleString(undefined, { minimumFractionDigits: 2 })}/mo.`,
    _mode: "demo",
  };
}

// ──────────── Deployment simulation (Flight Deck) ────────────
const STEP_PLAN = [
  ["preflight-policy", "Policy gate · org constraints replay", "PREFLIGHT", 2.0],
  ["preflight-plan", "terraform plan · drift check", "PREFLIGHT", 3.0],
  ["ignition-build", "Cloud Build · container bake", "IGNITION", 4.0],
  ["ignition-scan", "Artifact scan · CVE sweep", "IGNITION", 2.5],
  ["ascent-apply", "terraform apply · provisioning", "ASCENT", 5.0],
  ["ascent-smoke", "Smoke probes · golden signals", "ASCENT", 2.5],
  ["orbit-traffic", "Traffic shift · 100% to new revision", "ORBIT", 2.0],
];
const DEPLOYMENTS = new Map();

// Tests compress the timeline via globalThis.__CLOUDPILOT_SPEED (e.g. 0.12).
const speed = () => (typeof globalThis !== "undefined" && globalThis.__CLOUDPILOT_SPEED) || 1;

export function startDeployment(runId, { chaos = false } = {}) {
  const id = `dep-${Math.random().toString(36).slice(2, 10)}`;
  DEPLOYMENTS.set(id, { t0: Date.now() / 1000, runId, failStep: chaos ? "ascent-apply" : null, failedAt: null });
  return getDeployment(id);
}

export function retryDeployment(id) {
  const dep = DEPLOYMENTS.get(id);
  if (!dep) throw new Error("unknown deployment");
  dep.failStep = null;
  const sp = speed();
  let elapsed = 0;
  for (const [sid, , , dur] of STEP_PLAN) {
    elapsed += dur * sp;
    if (sid === dep.failedAt) break;
  }
  dep.t0 = Date.now() / 1000 - elapsed + 0.5 * sp;
  return getDeployment(id);
}

export function getDeployment(id) {
  const dep = DEPLOYMENTS.get(id);
  if (!dep) throw new Error("unknown deployment");
  const sp = speed();
  const elapsed = Date.now() / 1000 - dep.t0;
  const steps = [];
  const logTail = [];
  let cursor = 0, phase = "PREFLIGHT", halted = false;
  const total = STEP_PLAN.reduce((a, s) => a + s[3], 0) * sp;
  for (const [sid, name, ph, dur] of STEP_PLAN) {
    const d = dur * sp;
    let status;
    if (halted) status = "pending";
    else if (elapsed >= cursor + d) {
      if (dep.failStep === sid) { status = "failed"; halted = true; dep.failedAt = sid; logTail.push(`[${sid}] ERROR: step failed — see diagnosis`); }
      else { status = "success"; logTail.push(`[${sid}] ✓ ${name} (${dur.toFixed(1)}s)`); }
    } else if (elapsed >= cursor) { status = "running"; phase = ph; logTail.push(`[${sid}] … ${name}`); }
    else status = "pending";
    steps.push({ id: sid, name, phase: ph, status, duration_ms: status === "success" ? Math.round(dur * 1000) : null, log: null });
    cursor += d;
  }
  const done = steps.filter((s) => s.status === "success").length;
  let progress = halted ? Math.round((100 * done) / STEP_PLAN.length) : Math.round((100 * Math.min(elapsed, total)) / total);
  if (steps.every((s) => s.status === "success")) { phase = "ORBIT"; progress = 100; logTail.push("[orbit] 🛰  Architecture is live. Telemetry nominal."); }
  else if (halted) phase = steps.find((s) => s.status === "failed").phase;
  return { deployment_id: id, phase, progress, steps, log_tail: logTail.slice(-8) };
}

export function diagnose() {
  return {
    root_cause: {
      title: "Cloud SQL instance name collision in region us-central1",
      detail: "terraform apply failed because instance name 'orders-db' was used by a deleted instance still inside its 7-day reservation window. Gemini correlated the apply log with the project's audit trail (ingested in-context) and found the deletion event from 2026-06-07.",
      confidence: 0.97,
      error_line: "Error 409: The Cloud SQL instance already exists. When you delete an instance, you can't reuse the name for up to a week.",
      log_excerpt: [
        "google_sql_database_instance.orders-db: Creating...",
        "╷",
        "│ Error: Error, failed to create instance orders-db:",
        "│ googleapi: Error 409: The Cloud SQL instance already exists.",
        "│ When you delete an instance, you can't reuse the name for up to a week.",
        "╵",
      ],
    },
    patch: {
      file: "main.tf",
      diff: [
        { type: "ctx", text: 'resource "google_sql_database_instance" "orders-db" {' },
        { type: "del", text: '  name             = "orders-db"' },
        { type: "add", text: '  name             = "orders-db-${random_id.db_suffix.hex}"' },
        { type: "ctx", text: '  database_version = "POSTGRES_16"' },
        { type: "add", text: "" },
        { type: "add", text: 'resource "random_id" "db_suffix" { byte_length = 2 }' },
      ],
      explanation: "Suffix the instance name with a stable random id so re-creations never collide with the 7-day name reservation. Matches naming standard NAM-006 (immutable-resource suffixing).",
    },
    references: [
      { standard: "NAM-006", title: "Immutable resource naming with entropy suffixes" },
      { standard: "RES-002", title: "Recoverable delete windows for stateful services" },
    ],
  };
}

export function visionImport() {
  const nodes = [
    { id: "v-lb", type: "load_balancer", label: "Edge LB", position: { x: 80, y: 220 }, config: {} },
    { id: "v-armor", type: "cloud_armor", label: "Cloud Armor", position: { x: 80, y: 60 }, config: {} },
    { id: "v-api", type: "cloud_run", label: "API Service", position: { x: 360, y: 220 }, config: {} },
    { id: "v-worker", type: "cloud_run", label: "Worker", position: { x: 360, y: 420 }, config: {} },
    { id: "v-bus", type: "pubsub", label: "Event Bus", position: { x: 640, y: 320 }, config: {} },
    { id: "v-db", type: "cloud_sql", label: "Orders DB", position: { x: 640, y: 120 }, config: {} },
    { id: "v-llm", type: "gemini", label: "Gemini API", position: { x: 920, y: 220 }, config: {} },
  ];
  const edges = [
    { id: "ve-1", source: "v-armor", target: "v-lb", label: "WAF" },
    { id: "ve-2", source: "v-lb", target: "v-api", label: "HTTPS" },
    { id: "ve-3", source: "v-api", target: "v-db", label: "private IP" },
    { id: "ve-4", source: "v-api", target: "v-bus", label: "publish" },
    { id: "ve-5", source: "v-bus", target: "v-worker", label: "push sub" },
    { id: "ve-6", source: "v-worker", target: "v-llm", label: "inference" },
  ];
  return {
    graph: { nodes, edges },
    narrative: "Gemini read the whiteboard photo natively — no OCR pipeline. It identified 7 services, inferred the pub/sub fan-out from an arrow annotated 'async', and recognized the box labeled 'magic ai thing' as a Gemini inference call.",
    confidence: 0.94,
  };
}
